# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18srm6REk9ubI8HovoyEXmFG7uc6HSUzY
"""

import os
import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

# Tắt các cảnh báo không cần thiết của TensorFlow
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
tf.get_logger().setLevel('ERROR')

# --- 1. Tiêu đề và giao diện ---
st.set_page_config(page_title="AI vs Real Image Classifier", page_icon="🕵️")
st.title("🔍 Nhận diện Ảnh Thực tế & Ảnh AI")
st.write("Đồ án môn học: Nhập môn Thị giác máy tính - CS231")
st.write("Tải lên một bức ảnh bất kỳ để hệ thống kiểm tra xem đây là ảnh chụp thật hay do AI tạo ra nhé!")

# --- 2. Tải mô hình (Dùng cache để không load lại nhiều lần) ---
@st.cache_resource
def load_model():
    # Sửa lại tên file mô hình cho đúng với mô hình EfficientNetB0 bạn vừa lưu
    model_path = 'efficientnetB0_finetuned_30layers.keras'

    if not os.path.exists(model_path):
        st.error(f"❌ Không tìm thấy file mô hình tại: {model_path}. Hãy kiểm tra lại!")
        st.stop()

    return tf.keras.models.load_model(model_path)

model = load_model()

# --- 3. Xử lý Upload Ảnh ---
uploaded_file = st.file_uploader("Chọn một bức ảnh (JPG, JPEG, PNG, WEBP)...", type=["jpg", "jpeg", "png", "webp"])

if uploaded_file is not None:
    # Mở và hiển thị ảnh
    image = Image.open(uploaded_file)

    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.image(image, caption='Ảnh bạn vừa tải lên', use_container_width=True)

    st.write("---")

    # --- 4. Chạy dự đoán với EfficientNetB0 ---
    if st.button('🚀 Phân tích ảnh này', use_container_width=True):
        with st.spinner("Hệ thống đang quét các đặc trưng đa tầng..."):

            # Tiền xử lý ảnh: Đưa về RGB và kích thước 224x224
            if image.mode != 'RGB':
                image = image.convert('RGB')
            img_resized = image.resize((224, 224))

            # Chuyển thành mảng Numpy.
            # Điểm khác biệt: EfficientNet tự xử lý giá trị 0-255, không cần chia 255.0
            img_array = np.array(img_resized)
            img_array = np.expand_dims(img_array, axis=0)

            # Dự đoán
            prob = model.predict(img_array)[0][0]

            # In kết quả (Logic: 0 là AI_generated, 1 là Real)
            st.subheader("💡 Kết quả phân tích:")

            if prob > 0.5:
                st.success(f"📸 NHẬN ĐỊNH: Đây là **ẢNH THẬT (Real)**")
                st.metric("Độ tự tin (Confidence)", f"{prob * 100:.2f}%")
            else:
                st.error(f"🤖 NHẬN ĐỊNH: Đây là **ẢNH AI TẠO SINH**")
                st.metric("Độ tự tin (Confidence)", f"{(1 - prob) * 100:.2f}%")

            with st.expander("🔧 Xem chi tiết tham số kỹ thuật"):
                st.write(f"- Kiến trúc lõi: EfficientNetB0")
                st.write(f"- Kích thước đầu vào: 224x224x3")
                st.write(f"- Output Sigmoid Score: {prob:.6f}")
